--Kevin Stein  kestein@calpoly.edu
--Alex Spotnitz  aspotnitz@gmail.com
--Stephen Calabrese  sccalabr@calpoly.edu
--Alex Boltunov  aboltunov@gmail.com
--Luke Larson  lplarson@calpoly.edu
DROP TABLE SubscribesTo;
DROP TABLE Catalogues;
DROP TABLE Manufacturers;
DROP TABLE StoredAt;
DROP TABLE StoredIn;
DROP TABLE Bins;
DROP TABLE Items;
DROP TABLE Locations;
DROP TABLE FullfillerIds;
DROP TABLE FullfilledBy;
