
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.shopatron.api.coexprivate.core.v4;

import javax.annotation.Resource;
import javax.xml.ws.WebServiceContext;
import java.util.*;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-03T10:31:02.399-07:00
 * Generated source version: 2.7.5
 * 
 */

public class InventoryServiceImpl implements CoreService {

    @Resource
    WebServiceContext wContext;
                      
    private static final Logger LOG = Logger.getLogger(InventoryServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#createFulfillmentLocation(com.shopatron.api.coexprivate.core.v4.FulfillmentLocation  request )*
     */
    public int createFulfillmentLocation(com.shopatron.api.coexprivate.core.v4.FulfillmentLocation request) { 
        LOG.info("Executing operation createFulfillmentLocation");
       // System.out.println(request);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#createFulfiller(com.shopatron.api.coexprivate.core.v4.FulfillerRequest  request )*
     */
    public int createFulfiller(com.shopatron.api.coexprivate.core.v4.FulfillerRequest request) { 
        LOG.info("Executing operation createFulfiller");
        //System.out.println(request);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#getInventory(com.shopatron.api.coexprivate.core.v4.InventoryRequest  request )*
     */
    public java.util.List<com.shopatron.api.coexprivate.core.v4.InventoryResponse> getInventory(com.shopatron.api.coexprivate.core.v4.InventoryRequest request) { 
        LOG.info("Executing operation getInventory");
        //System.out.println(request);
        try {
            return getInventoryDistance.listInventory(request);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#refreshInventory(com.shopatron.api.coexprivate.core.v4.RefreshRequest  parameters )*
     */
    public java.lang.String refreshInventory(RefreshRequest parameters) { 
        LOG.info("Executing operation refreshInventory");
        //System.out.println(parameters);
        
		 return TrickleInventoryHelper.refreshInventory(parameters);
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#getFulfillmentLocationTypes(*
     */
    public java.util.List<com.shopatron.api.coexprivate.core.v4.FulfillmentLocationType> getFulfillmentLocationTypes() { 
        LOG.info("Executing operation getFulfillmentLocationTypes");
        try {
            java.util.List<FulfillmentLocationType> _return = GetFulfillmentLocationTypesHelper.getFulfillmentLocationTypes();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#getBins(com.shopatron.api.coexprivate.core.v4.BinRequest  request )*
     */
    public com.shopatron.api.coexprivate.core.v4.BinResponse getBins(com.shopatron.api.coexprivate.core.v4.BinRequest request) { 
        LOG.info("Executing operation getBins");
        //System.out.println(request);
        
        return GetBinsHelper.getBins(request);
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#createBin(com.shopatron.api.coexprivate.core.v4.Bin  request )*
     */
    public java.math.BigInteger createBin(com.shopatron.api.coexprivate.core.v4.Bin request) { 
        LOG.info("Executing operation createBin");
        //System.out.println(request);
        try {
            java.math.BigInteger _return = CreateBinHelper.createBin(request);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#adjustInventory(com.shopatron.api.coexprivate.core.v4.AdjustRequest  parameter )*
     */
    public java.lang.String adjustInventory(AdjustRequest parameter) { 
        LOG.info("Executing operation adjustInventory");
        //System.out.println(parameter);
        
		 return TrickleInventoryHelper.adjustInventory(parameter);
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#deallocateInventory(com.shopatron.api.coexprivate.core.v4.UpdateRequest  request )*
     */
    public void deallocateInventory(com.shopatron.api.coexprivate.core.v4.UpdateRequest request) { 
        LOG.info("Executing operation deallocateInventory");
        //System.out.println(request);
        int response = DeallocateHelper.deallocateInventory(request);
      
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#getBinStatuses(*
     */
    public java.util.List<com.shopatron.api.coexprivate.core.v4.BinStatus> getBinStatuses() { 
        LOG.info("Executing operation getBinStatuses");
        try {
            java.util.List<BinStatus> _return = GetBinStatusesHelper.getBinStatuses();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#getFulfillerStatus(int  fulfillerID )*
     */
    public int getFulfillerStatus(int fulfillerID) { 
        LOG.info("Executing operation getFulfillerStatus");
        //System.out.println(fulfillerID);
        try {
            return getFulfillerStatusHelper.getStatus(fulfillerID);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            return -1; 
        }
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#fulfillInventory(com.shopatron.api.coexprivate.core.v4.UpdateRequest  request )*
     */
    public void fulfillInventory(com.shopatron.api.coexprivate.core.v4.UpdateRequest request) { 
        LOG.info("Executing operation fulfillInventory");
        //System.out.println(request);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#allocateInventory(com.shopatron.api.coexprivate.core.v4.UpdateRequest  request )*
     */
    public void allocateInventory(com.shopatron.api.coexprivate.core.v4.UpdateRequest request) { 
        LOG.info("Executing operation allocateInventory");
        //System.out.println(request);
        int response = AllocateInventoryHelper.allocateInventory(request);
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#getFulfillmentLocations(com.shopatron.api.coexprivate.core.v4.OrderRequest  request )*
     */
    public java.util.List<com.shopatron.api.coexprivate.core.v4.AssignmentResponse> getFulfillmentLocations(com.shopatron.api.coexprivate.core.v4.OrderRequest request) { 
        LOG.info("Executing operation getFulfillmentLocations");
        //System.out.println(request);
        try {
            return getFulfillmentLocationsHelper.getLocations(request);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.shopatron.api.coexprivate.core.v4.CoreService#getBinTypes(*
     */
    public java.util.List<com.shopatron.api.coexprivate.core.v4.BinType> getBinTypes() { 
        LOG.info("Executing operation getBinTypes");
        
        return GetBinTypeHelper.getBinTypesResponse().getGetBinTypesReturn();
    }

}
