var WSDL = (function() {
    "use strict";
    _.templateSettings = {
      interpolate: /\{\{(.+?)\}\}/g,
      evaluate: /\{\%(.+?)\%\}/g
    };
    return {
        createFulfiller: _.template('<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v4="http://v4.core.coexprivate.api.shopatron.com"> <soapenv:Header/> <soapenv:Body> <v4:createFulfiller> <v4:request> <v4:FulfillerID>{{ FulfillerID }}</v4:FulfillerID> <v4:Name>{{ Name }}</v4:Name> </v4:request> </v4:createFulfiller> </soapenv:Body> </soapenv:Envelope>'),
        createFulfillmentLocation: _.template('<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v4="http://v4.core.coexprivate.api.shopatron.com"> <soapenv:Header/> <soapenv:Body> <v4:createFulfillmentLocation> <v4:request> <v4:FulfillerID>{{ FulfillerID }}</v4:FulfillerID> <v4:RetailerLocationID>{{ RetailerLocationID }}</v4:RetailerLocationID> <v4:ExternalLocationID>{{ ExternalLocationID }}</v4:ExternalLocationID> <v4:LocationName>{{ LocationName }}</v4:LocationName> <v4:LocationType>{{ LocationType }}</v4:LocationType> <v4:Latitude>{{ Latitude }}</v4:Latitude> <v4:Longitude>{{ Longitude }}</v4:Longitude> <v4:Status>{{ Status }}</v4:Status> <v4:CountryCode>{{ CountryCode }}</v4:CountryCode> </v4:request> </v4:createFulfillmentLocation> </soapenv:Body> </soapenv:Envelope>'),
        createBin: _.template('<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v4="http://v4.core.coexprivate.api.shopatron.com"> <soapenv:Header/> <soapenv:Body> <v4:createBin> <v4:request> <v4:FulfillerID>{{ FulfillerID }}</v4:FulfillerID> <v4:BinID>{{ BinID }}</v4:BinID> <v4:FulfillerLocationID>{{ FulfillerLocationID }}</v4:FulfillerLocationID> <v4:BinType>{{ BinType }}</v4:BinType> <v4:BinStatus>{{ BinStatus }}</v4:BinStatus> <v4:Name>{{ Name }}</v4:Name> </v4:request> </v4:createBin> </soapenv:Body> </soapenv:Envelope>'),
        refreshInventory: _.template('<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v4="http://v4.core.coexprivate.api.shopatron.com"> <soapenv:Header/> <soapenv:Body> <v4:RefreshRequest> <v4:FulfillerID>{{ FulfillerID }}</v4:FulfillerID> <v4:LocationName>{{ LocationName }}</v4:LocationName> <v4:Items> {% _.each(Items, function(Item) { %} <v4:items> <v4:PartNumber>{{ Item.PartNumber }}</v4:PartNumber> <v4:UPC>{{ Item.UPC }}</v4:UPC> <v4:BinID>{{ Item.BinID }}</v4:BinID> <v4:Quantity>{{ Item.Quantity }}</v4:Quantity> <v4:LTD>{{ Item.LTD }}</v4:LTD> <v4:SafetyStock>{{ Item.SafetyStock }}</v4:SafetyStock> </v4:items> {% }); %} </v4:Items> </v4:RefreshRequest> </soapenv:Body> </soapenv:Envelope>')
    };
})();
